config/routes.rb
Memoram::Application.routes.draw do

  resources :cards

  get "kies/kaart" => "cards#assortment", :as => "assortment"
  get "overzicht" => "cards#index", :as => "overzicht"
  get "ontwerp/kaart" => "cards#new", :as => "ontwerp"

  root :to => "cards#startpage"

end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id                  :integer          not null, primary key
#  birthday            :date
#  deceasedon          :date
#  poem                :text
#  province            :string(255)
#  birthplace          :string(255)
#  lastresidence       :string(255)
#  signed              :text
#  created_at          :datetime
#  updated_at          :datetime
#  input_front         :text
#  name                :string(255)
#  parting_information :text
#  first_name          :string(255)
#  last_name           :string(255)
#  street_name         :string(255)
#  house_number        :string(255)
#  addition            :string(255)
#  zip_code            :string(255)
#  address             :string(255)
#  email               :string(255)
#  phone_number        :string(255)
#  shipping_date       :date
#  quantity            :string(255)
#  country             :string(255)
#

class Card < ActiveRecord::Base
	has_many :pictures, :dependent => :destroy
	#validates :quantity, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than => 10, :less_than => 1000}
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id                 :integer          not null, primary key
#  created_at         :datetime
#  updated_at         :datetime
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  card_id            :integer
#

class Picture < ActiveRecord::Base
	belongs_to :card

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },
	 :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
      :url => "/system/:attachment/:id/:style/:filename"

    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	def index
	@q = Card.search(params[:q])
	@cards = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 7)
	#@cards = Card.all
	end
	
	def show
    @card = Card.find(params[:id])
       respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "#{@card.name}",
        	:template => 'cards/pdf.html.slim',
        	:page_size => "A4",
        	:disposition => 'attachment',
        	:no_background => true,
        	:orientation => 'Landscape'
    	end
		end
	end
	
	def new
		@cards = Card.new
        
		
	end
	
	def edit
		@card = Card.find(params[:id])
	end
	
	def create
	  @card = Card.new(card_params)
	  if @card.save 
	  	redirect_to action: "index"
	  	if params[:images]
        #===== The magic is here ;)
	        params[:images].each { |image|
	          @card.pictures.create(image: image)
	        }
      		end
  		end
	  
  end
	
	def update
		@card = Card.find(params[:id])
		@card.update_attributes(card_params)
    redirect_to cards_path	
	end
	
	def destroy
 		@card = Card.find(params[:id])
    @card.destroy
    redirect_to cards_path
	end	

	def startpage
		@q = Card.search(params[:q])
		@cards = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 7)
	end

	def assortment

	end
	
	private
  def card_params
  	params.require(:card).permit(:name, :birthday, :deceasedon, :poem, :province, :birthplace, :lastresidence, :signed, :picture, :input_front, :parting_information, :first_name,
																	:last_name, :street_name, :house_number, :addition, :zip_code, :address, :email, :phone_number, :shipping_date, :quantity, :country)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_input.html.slim
.container.bg-color
	
	ul.choose_step
		li.active= link_to 'Voorkant', :class => 'step_one'
		li= link_to 'Binnenkant', :class => 'step_two'
		li= link_to 'Voorbeeld', :class => 'step_three'
		li= link_to 'Afronden', :class => 'step_four'

	= form_for :card, url: cards_path, :html => { :multipart => true } do |f|
		.step#one.show
			.content

				= f.label :pictures
					= file_field_tag "images[]", type: :file, multiple: true, :class => 'file'
					= file_field_tag "images[]", type: :file, multiple: true, :class => 'file_one'
				
				= f.text_area :input_front, :class => ['input_front', 'form-control']
				.editfunctions
					input#color1 name="color1" type="text" value="#333399"
						p lettertype
						#myform
						  select#fs
						    option value="Arial"  Arial
						    option value=("Verdana ")  Verdana
						    option value=("Impact ")  Impact
						    option value=("Comic Sans MS")  Comic Sans MS
						p Text grootte
						#slider

		.step#two
			.content 
				= f.text_area :poem, :placeholder => "Gedicht of verhaal", :class => ['poem', 'form-control'], autofocus: true
				= f.text_field :name, :placeholder => "Naam", :class => ['name', 'form-control']
				= f.text_field :birthplace, :placeholder => "Geboorte plaats", :class => ['birthplace', 'form-control']
				= f.text_field :lastresidence, :placeholder => "Laatste woonplaats", :class => ['lastresidence', 'form-control']
				= f.date_field :birthday, :placeholder => "Geboorte datum", :class => ['birthday', 'form-control']
				= f.date_field :deceasedon, :placeholder => "Overleden op", :class => ['deceasedon', 'form-control']
				= f.text_area :signed, :placeholder => "Ondertekend door", :class => ['signed', 'form-control']
				= f.text_area :parting_information, :placeholder => "ASD?", :class => ['parting_information', 'form-control']
				= f.select :province, ["Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg", "Noord-Brabant", "Noord-Holland", "Overijssel", "Utrecht", "Zeeland", "Zuid-Holland"]

				#menu = image_tag "menu.png"
				#thumb
				 	ul
				    li = image_tag "1.jpg"
				    li = image_tag "2.jpg"
				    br
				    li = image_tag "3.jpg"
				    li = image_tag "4.jpg"
				    br
				    li = image_tag "5.jpg"
				    li = image_tag "6.jpg"
				    br
				    li = image_tag "7.jpg"
				    li = image_tag "white.png", :placeholder => "Geen afbeelding"

		.step#three
			.content
		
		.step#four
			.content
				= f.text_field :first_name, :placeholder => "Voornaam", :class => ['name', 'form-control']
				= f.text_field :last_name, :placeholder => "Achternaam", :class => ['name', 'form-control']
				= f.text_field :street_name, :placeholder => "Straat", :class => ['name', 'form-control']
				= f.text_field :house_number, :placeholder => "Huisnummer", :class => ['name', 'form-control']
				= f.text_field :addition, :placeholder => "Toevoeging", :class => ['name', 'form-control']
				= f.text_field :zip_code, :placeholder => "Postcode", :class => ['name', 'form-control']
				= f.text_field :address, :placeholder => "Dorp of stad", :class => ['name', 'form-control']
				= f.text_field :email, :placeholder => "E-mail", :class => ['name', 'form-control']
				= f.text_field :phone_number, :placeholder => "Telefoon nummer", :class => ['name', 'form-control']
				= f.date_field :shipping_date, :placeholder => "Verzend datum", :class => ['shipping_date', 'form-control']
				= f.text_field :quantity, :placeholder => "Aantal kaarten", :class => ['name', 'form-control']
				= f.text_field :country, :placeholder => "Land", :class => ['name', 'form-control']

				= f.submit "Afronden"
		
		.card.show
			#canvas
					.voorkant-text
						p.input_front1.changeMe
					.image
							img
								

					.upload-preview_one
						img
								
		.card
			
		.cardright
			p.poem1 
			h2.name1
			p.birthplace1
			p.lastresidence1
			br
			p.birthday1
			p.deceasedon1
			br
			p.signed1
			p.parting_information1

		.knoppen
			a.btn.btn-default.prev vorige
			a.btn.btn-warning.next volgende
				

		
	
	

app/views/cards/assortment.html.slim
.container
	.row
		.col-sm-6.col-md-4
			.thumbnail
				.caption
				p Start met een lege kaart:
				= link_to "lege kaart ontwerpen", ontwerp_path
				= image_tag ("rouwkaartleeg.png")

		.col-sm-6.col-md-4
			.thumbnail
				.caption
				p test
				= image_tag ("rouwkaart.png")

		.col-sm-6.col-md-4
			.thumbnail
				.caption
				p test
				= image_tag ("rouwkaart.png")

app/views/cards/edit.html.slim
= render "cards/input"

app/views/cards/index.html.slim
.container
	.row
		.col-sm-6.col-md-4.nederland
			    .thumbnail.nederland
			    	.caption
				    	= search_form_for @q do |f|

							.input-group
							  
							  = f.text_field :lastresidence_or_province_or_name_cont, :class => 'form-control', :placeholder => "Zoek op plaats, naam o.i.d."
							  
							  span.input-group-btn
							   	= f.submit "Zoeken", :class => 'button btn btn-default'

		      	
		      		<img id="Image-Maps-Com-image-maps-2014-11-26-071334" src="http://www.image-maps.com/m/private/38269/37452-qo7vj9hre4opl0uqmpijsfa794_nederland-groen.png" border="0" width="260" height="307" orgWidth="260" orgHeight="307" usemap="#image-maps-2014-11-26-071334" alt="" />
					<map name="image-maps-2014-11-26-071334" id="ImageMapsCom-image-maps-2014-11-26-071334">
					<area shape="rect" coords="258,305,260,307" alt="Image Map" style="outline:none;" title="Image Map" href="http://www.image-maps.com/index.php?aff=mapped_users_38269" />
					<area id="Friesland" alt="Overlijdens advertenties Friesland" title="Friesland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Friesland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="201,1,128,18,118,24,104,37,115,43,135,70,148,74,174,77,197,71,202,64,196,53,185,47,191,34,194,24,194,15" style="outline:none;" target="_self"     />
					<area id="Groningen" alt="Overlijdens advertenties Groningen" title="Groningen" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Groningen&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="195,14,203,22,199,30,197,42,208,37,222,42,241,52,249,62,253,69,259,36,236,12,225,10" style="outline:none;" target="_self"     />
					<area id="Drenthe" alt="Overlijdens advertenties Drenthe" title="Drenthe" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Drenthe&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="204,49,208,62,206,71,198,73,194,79,196,86,205,94,225,91,240,94,246,82,247,71,230,52,222,47,213,41,210,40" style="outline:none;" target="_self"     />
					<area id="Overijsel" alt="Overlijdens advertenties Overijsel" title="Overijsel" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Overijsel&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="187,80,173,82,179,95,179,104,170,106,177,113,187,114,191,125,190,134,196,142,209,140,218,146,233,152,251,129,229,118,225,105,221,98,215,100,209,105,199,100,191,97,188,89" style="outline:none;" target="_self"     />
					<area id="Flevoland" alt="Overlijdens advertenties Flevoland" title="Flevoland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Flevoland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="160,80,153,90,150,106,123,130,142,139,168,110,168,102,179,97,173,88" style="outline:none;" target="_self"     />
					<area id="Gelderland" alt="Overlijdens advertenties Gelderland" title="Gelderland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Gelderland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="172,118,145,145,153,165,155,177,126,177,119,188,125,195,134,193,147,186,162,188,172,193,215,182,232,160,209,152,198,148,186,146,185,126,184,119" style="outline:none;" target="_self"     />
					<area id="Noord-Holland" alt="Overlijdens advertenties Noord-Holland" title="Noord-Holland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Noord-Holland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="102,42,94,58,81,133,86,144,101,142,115,138,125,146,129,138,113,129,117,100,130,95" style="outline:none;" target="_self"     />
					<area id="Utrecht" alt="Overlijdens advertenties Utrecht" title="Utrecht" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Utrecht&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="133,142,126,152,116,147,112,142,102,146,106,155,111,162,106,169,118,170,135,171,148,171,148,165" style="outline:none;" target="_self"     />
					<area id="Zuid-Holland" alt="Overlijdens advertenties Zuid-Holland" title="Zuid-Holland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Zuid-Holland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="77,139,54,170,47,182,66,194,84,201,91,194,104,190,116,185,121,176,109,177,102,176,101,171,103,160,96,150" style="outline:none;" target="_self"     />
					<area id="Noord-Brabant" alt="Overlijdens advertenties Noord-Brabant" title="Noord-Brabant" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Noord-Brabant&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="170,200,151,193,133,200,121,201,114,195,106,191,99,195,103,204,81,206,70,207,60,213,64,236,107,234,130,243,149,248,168,241,172,236,167,226,167,218,170,217,176,216,178,211" style="outline:none;" target="_self"     />
					<area id="Limburg" alt="Overlijdens advertenties Limburg" title="Limburg" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Limburg&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="181,205,185,219,176,222,173,237,165,246,158,251,163,258,159,298,187,308,197,230" style="outline:none;" target="_self"     />
					<area id="Zeeland" alt="Overlijdens advertenties Zeeland" title="Zeeland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Zeeland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="29,198,4,221,1,244,9,253,38,252,55,250,61,241,60,228,56,214,56,210,48,204" style="outline:none;" target="_self"     />
					</map>

		- @cards.order("id DESC").each do |t|
		  .col-sm-6.col-md-4
		    .thumbnail
		      .caption
		        	h3.text = link_to t.name, card_path(t)
		        	hr
		        	p.text = t.birthplace
		        	p.text = "#{ t.birthday.strftime("%d-%m-%y")} " "|" " #{  t.deceasedon.strftime("%d-%m-%y") }"
		        	.message = link_to "Bekijk dit bericht", card_path(t), :class => "btn btn-primary"


	= will_paginate @cards





	  

app/views/cards/new.html.slim
= render "cards/input"

app/views/cards/pdf.html.slim
head
	= wicked_pdf_stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
	= wicked_pdf_javascript_include_tag "application", "data-turbolinks-track" => true 
	meta charset="utf-8"
.container
	.rouwbericht
		- @card.pictures.each do |p|
			= wicked_pdf_image_tag p.image, :class => "card-background"

	.rouwbericht-text
		p.poem = @card.poem
		h2.name = @card.name
		p.birthday = @card.birthday.strftime("%d-%m-%y") 
		p.deceasedon = @card.deceasedon.strftime("%d-%m-%y")
		p.place = @card.birthplace
		p.lastresidence = @card.lastresidence
		p.signed = @card.signed
		p = @card.parting_information 


	
	= button_to "verwijder", @card, :method => :delete
	= link_to "aanpassen", edit_card_path
	= link_to "Download PDF", :action => "show", :format => :pdf

app/views/cards/show.html.slim
.container
	.rouwbericht
		- @card.pictures.each do |p|
			= image_tag p.image, :class => "card-background"

	.rouwbericht-text
		p.poem = @card.poem
		h2.name = @card.name
		p.birthday = @card.birthday.strftime("%d-%m-%y") 
		p.deceasedon = @card.deceasedon.strftime("%d-%m-%y")
		p.place = @card.birthplace
		p.lastresidence = @card.lastresidence
		br
		p.signed = @card.signed
		p = @card.parting_information 


	
	= button_to "verwijder", @card, :method => :delete
	= link_to "aanpassen", edit_card_path
	= link_to "Download PDF", :action => "show", :format => :pdf

app/views/cards/startpage.html.slim
.container
	.row
		.col-sm-6.col-md-4
			.thumbnail
				.caption
					h3 Rouwkaart maken
					hr
					.cardimg = image_tag ("rouwkaart.png")
					p Maak de rouwkaart geheel naar eigen wens. Je kunt hier zelf de foto’s, teksten, kleuren, lettertype. bepalen. Ook mogelijk om direct naar je familie toe te sturen. Als je de kaart vandaag maakt wordt de kaart vandaag op de post gedaan.
					= link_to "Ontwerp Rouwkaart", new_card_path, :class => "btn btn-primary"
		.col-sm-6.col-md-4
			.thumbnail
				.caption
					h3 Overlijdensbericht maken
					hr
					.cardimg = image_tag ("rouwbericht.png")
					p Bij het bestellen van rouwkaarten krijgt u gratis een overlijdensbericht, hiermee kunt u mensen op de hoogte stellen waarvan u de adressen niet heeft of in het buitenland wonen. De advertentie kunt u ook doorsturen via de mail.
					= link_to "Ontwerp Rouwbericht", new_card_path, :class => "btn btn-primary"

		.col-sm-6.col-md-4.nederland
			    .thumbnail.nederland
			    	.caption
				    	= search_form_for @q do |f|

							.input-group
							  
							  = f.text_field :lastresidence_or_province_or_name_cont, :class => 'form-control', :placeholder => "Zoek op plaats, naam o.i.d."
							  
							  span.input-group-btn
							   	= f.submit "Zoeken", :class => 'button btn btn-default'

		      	
		      		<img id="Image-Maps-Com-image-maps-2014-11-26-071334" src="http://www.image-maps.com/m/private/38269/37452-qo7vj9hre4opl0uqmpijsfa794_nederland-groen.png" border="0" width="260" height="307" orgWidth="260" orgHeight="307" usemap="#image-maps-2014-11-26-071334" alt="" />
					<map name="image-maps-2014-11-26-071334" id="ImageMapsCom-image-maps-2014-11-26-071334">
					<area shape="rect" coords="258,305,260,307" alt="Image Map" style="outline:none;" title="Image Map" href="http://www.image-maps.com/index.php?aff=mapped_users_38269" />
					<area id="Friesland" alt="Overlijdens advertenties Friesland" title="Friesland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Friesland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="201,1,128,18,118,24,104,37,115,43,135,70,148,74,174,77,197,71,202,64,196,53,185,47,191,34,194,24,194,15" style="outline:none;" target="_self"     />
					<area id="Groningen" alt="Overlijdens advertenties Groningen" title="Groningen" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Groningen&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="195,14,203,22,199,30,197,42,208,37,222,42,241,52,249,62,253,69,259,36,236,12,225,10" style="outline:none;" target="_self"     />
					<area id="Drenthe" alt="Overlijdens advertenties Drenthe" title="Drenthe" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Drenthe&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="204,49,208,62,206,71,198,73,194,79,196,86,205,94,225,91,240,94,246,82,247,71,230,52,222,47,213,41,210,40" style="outline:none;" target="_self"     />
					<area id="Overijsel" alt="Overlijdens advertenties Overijsel" title="Overijsel" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Overijsel&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="187,80,173,82,179,95,179,104,170,106,177,113,187,114,191,125,190,134,196,142,209,140,218,146,233,152,251,129,229,118,225,105,221,98,215,100,209,105,199,100,191,97,188,89" style="outline:none;" target="_self"     />
					<area id="Flevoland" alt="Overlijdens advertenties Flevoland" title="Flevoland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Flevoland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="160,80,153,90,150,106,123,130,142,139,168,110,168,102,179,97,173,88" style="outline:none;" target="_self"     />
					<area id="Gelderland" alt="Overlijdens advertenties Gelderland" title="Gelderland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Gelderland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="172,118,145,145,153,165,155,177,126,177,119,188,125,195,134,193,147,186,162,188,172,193,215,182,232,160,209,152,198,148,186,146,185,126,184,119" style="outline:none;" target="_self"     />
					<area id="Noord-Holland" alt="Overlijdens advertenties Noord-Holland" title="Noord-Holland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Noord-Holland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="102,42,94,58,81,133,86,144,101,142,115,138,125,146,129,138,113,129,117,100,130,95" style="outline:none;" target="_self"     />
					<area id="Utrecht" alt="Overlijdens advertenties Utrecht" title="Utrecht" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Utrecht&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="133,142,126,152,116,147,112,142,102,146,106,155,111,162,106,169,118,170,135,171,148,171,148,165" style="outline:none;" target="_self"     />
					<area id="Zuid-Holland" alt="Overlijdens advertenties Zuid-Holland" title="Zuid-Holland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Zuid-Holland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="77,139,54,170,47,182,66,194,84,201,91,194,104,190,116,185,121,176,109,177,102,176,101,171,103,160,96,150" style="outline:none;" target="_self"     />
					<area id="Noord-Brabant" alt="Overlijdens advertenties Noord-Brabant" title="Noord-Brabant" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Noord-Brabant&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="170,200,151,193,133,200,121,201,114,195,106,191,99,195,103,204,81,206,70,207,60,213,64,236,107,234,130,243,149,248,168,241,172,236,167,226,167,218,170,217,176,216,178,211" style="outline:none;" target="_self"     />
					<area id="Limburg" alt="Overlijdens advertenties Limburg" title="Limburg" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Limburg&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="181,205,185,219,176,222,173,237,165,246,158,251,163,258,159,298,187,308,197,230" style="outline:none;" target="_self"     />
					<area id="Zeeland" alt="Overlijdens advertenties Zeeland" title="Zeeland" href="/cards?utf8=✓&q%5Bprovince_cont%5D=Zeeland&q%5Blastresidence%5D=&commit=Zoeken" shape="poly" coords="29,198,4,221,1,244,9,253,38,252,55,250,61,241,60,228,56,214,56,210,48,204" style="outline:none;" target="_self"     />
					</map>

		.col-sm-6.col-md-8
			.thumbnail
				.caption
					h3 Maak de Rouwkaart bijzonder en persoonlijk.
					hr 
					= image_tag ("enveloppe.png")
					li 	Keus uit eigen foto’s of uit de fotogalerij
					li	Eigen teksten en plaatsing van de tekst
					li	Lettertype en kleur
					li	Papiersoort mat of glans(beste kwaliteit 300 grams)
					li	Direct versturen naar je familie en vrienden

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-static-top role="navigation" 
  .container
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/"  Memoram
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        li
          = link_to "Home", root_path
        li
          = link_to "Rouwkaart maken", assortment_path
        li
          = link_to "rouwberichten", overzicht_path
        li
          a href="#contact"  Contact
       

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memoram</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>


  <%= csrf_meta_tags %>
  
</head>
<body>
	

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>